{% set name = "azure-ai-documentintelligence" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 246ec4d95316585175b38f687ffde17b394620221af966f635cec15a81c5b7cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.6.0
    - python >={{ python_min }}
    - isodate >=0.6.1
    - azure-core >=1.30.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.ai.documentintelligence
    - azure.ai.documentintelligence._operations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk
  summary: Microsoft Azure AI Document Intelligence Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
