{% set name = "azure-ai-documentintelligence" %}
{% set version = "1.0.0b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1aa36f0617b0c129fdc82b039b7084fd5b69af08e8e0cb500108b9f6efd61b36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - isodate >=0.6.1
    - azure-core >=1.30.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.ai.documentintelligence
    - azure.ai.documentintelligence._operations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk
  summary: Microsoft Azure AI Document Intelligence Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
